default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: final_capstone_rails_api_development
  username: postgres
  password: tshepi14c

test:
  <<: *default
  database: final_capstone_rails_api_test
  username: postgres
  password: tshepi14c

production:
  <<: *default
  database: final_capstone_rails_api_production
  username: final_capstone_rails_api
  password: <%= ENV["FINAL_CAPSTONE_RAILS_API_DATABASE_PASSWORD"] %>
